# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarQubePrepare@4
  inputs:
      SonarQube: 'SonarQube.Net'
      scannerMode: 'MSBuild'
      projectKey: '.NetApp'
      projectName: '.NetApp'

- task: SonarQubePreBuild@1
  inputs:
    projectKey: '.NetApp'
    projectName: '.NetApp'
    projectVersion: '1.0'

- task: SonarQubeAnalyze@4

- task: SonarQubePostTest@1

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'